const RouteName = {
    SPLSH: "SplashScreen",
    LOGIN_SCREEN: "LoginScreen",
    REGISTER_SCREEN: "Register",
    HOME_SCREEN: "HomeScreen",
    TAB_HOME: "Homes",
    TAB_SPECIALIST: "Specialist",
    TAB_HISTORY: "History",
    TAB_EXERCISE: "Appointments",
    DoctorCall: "Call",
    TAB_PROFILE: "Profile",

    EXERCISE_DETAIL: "ExerciseDetail",
    CHANGE_PASSWORD: "ChangePassword",
    EDIT_PROFILE: "EditProfile",
    PAYMENT: "Payment",
    THANK_YOU: "ThankYou",
    VIDEOCALL: "VideoCall",
    AUDIOCALL_SET: "AudioCall",
    REGIATRAION_SUCCESSFULL: "RegistrationSuccessful",
    THANKS_SCREEN: "ThankYouScreens",
    REVIEWS_SCREEN: "DraweReviesScreen",
    AUDIOCALL_VIDEOCALL: 'AudioCallandVideocall',
    PRESCTION: 'Prescription',
   
    END_CALL: 'EndCallScreen',
    SAVECARD_SCREEN: 'SaveCardScreen',
    PAYNOW_SCREEN: 'PayNowScreen',
    DRAWERSCREEN_HOME: 'DrawerHomeScreen',
    DRAWER_EXCERSIE: 'DrawerExcersize',
    DRAWER_NOTIFICATION: 'DrawerNotification',
    DOCTORE_LISTINGPAGE: 'DoctoreListingscreen',
    CHART_DOCTORE_SCREEN: 'DrawerChartScreen',
    DRAWER_HELPS_SCREEN: 'DrawerHelpScreen',
    DOCTORE_DETAILES_SCREEN: 'DoctoreDetailesScreen',
    DOCTORE_MAP_LOCATIONS: 'Doctoremapscreen',
    CHART_SCREEN_PERSON: 'ChartScreen',
    LOGIN_PATINT_TAB_SCREEN: 'LoginandPatientTab',
    OTP_VERYFY_SCREEN: 'OtpVeryfiveScreen',
    DRAWER_VIDEOCALL: 'DrawerVideocallScreen',
    DRAWER_LISTING_SCREEN: 'DrawerListingScreenn',
    TAB_PROFILE_SCREEN: 'TabProfile',    
    DRAWERNEWS_DETAILES_SCREEN: 'DraweNewsDeatilesScreen',
    DRAWER_PAYMENT_SCREEN: "DrawerPaymentScreen",
    HOME_TAB_SET: "Homes",
    MY_COURSES_TAB : "Appointments",
    EXAM_TAB : "Patient",
    WHISHILIST_TAB : "Profile",
    TAB_NEARBY : "Nearby",
    MAP_SCREEN: "MapLocation",
    CATEGORY_LIST_SCREEN: "CategoryList",
    BOOKAPPOINTMENT: "BookAppointment",
    HOME_SEARECH: "HomeSearchScreen",
    GET_STARTED_SCREEN: "GetstartedSliderscreen",
    NOTIFICATION_DRAWER: "DrawerNavigationNotification"

}
export default RouteName;